import { WebsiteCategory } from "@/models/links/enum/web-category.enum";

export const getNameCategory = (category: WebsiteCategory): string => ({
    [WebsiteCategory.DEVELOPMENT]: 'Desarrollo',
    [WebsiteCategory.STREAMING]: 'Streaming',
    [WebsiteCategory.DOCUMENTATION]: 'Documentación',
    [WebsiteCategory.GAMING]: 'Juegos',
    [WebsiteCategory.SOCIAL_MEDIA]: 'Redes Sociales',
    [WebsiteCategory.E_COMMERCE]: 'Comercio Electrónico',
    [WebsiteCategory.EDUCATION]: 'Educación',
    [WebsiteCategory.NEWS]: 'Noticias',
    [WebsiteCategory.FINANCE]: 'Finanzas',
    [WebsiteCategory.HEALTH]: 'Salud',
    [WebsiteCategory.PRODUCTIVITY]: 'Productividad',
    [WebsiteCategory.DESIGN]: 'Diseño',
    [WebsiteCategory.MUSIC]: 'Música',
    [WebsiteCategory.VIDEO]: 'Video',
    [WebsiteCategory.CLOUD_STORAGE]: 'Almacenamiento en la Nube',
    [WebsiteCategory.EMAIL]: 'Correo Electrónico',
    [WebsiteCategory.FORUM]: 'Foro',
    [WebsiteCategory.BLOG]: 'Blog',
    [WebsiteCategory.TRAVEL]: 'Viajes',
    [WebsiteCategory.FOOD]: 'Comida',
    [WebsiteCategory.SPORTS]: 'Deportes',
    [WebsiteCategory.TECHNOLOGY]: 'Tecnología',
    [WebsiteCategory.ENTERTAINMENT]: 'Entretenimiento',
    [WebsiteCategory.BUSINESS]: 'Negocio',
    [WebsiteCategory.MARKETING]: 'Marketing',
    [WebsiteCategory.SCIENCE]: 'Ciencia',
    [WebsiteCategory.GOVERNMENT]: 'Gobierno',
    [WebsiteCategory.NONPROFIT]: 'No-Gobierno',
    [WebsiteCategory.PERSONAL]: 'Personal',
    [WebsiteCategory.OTHER]: 'Otro'
})[category] || 'Otro';